### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/UI-kit#26]
Проверь также другие страницы. Если у тебя все сходится, скинь пожалуйста картинки по которым сверяешься
![image](https://user-images.githubusercontent.com/66846004/111606437-42ee2d80-87e8-11eb-9716-922bb22b0340.png)

**Comment by Sprashivaite** [comment]
Под PP делал под ширину 1440px. Если ширина больше, то текст увеличивается.

**Comment by kate-fsd** [comment]
Если ширина больше 1440 то тоже должно сходиться, не увеличивай шрифт

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/112202598-9e724e00-8c22-11eb-8cc1-d248da6a7922.png)
![image](https://user-images.githubusercontent.com/66846004/112202645-aaf6a680-8c22-11eb-96eb-3ea01db410dc.png)

**Comment by kate-fsd** [comment]
Смотри, в макете ширина основного контента -1160 (от лого до кнопки на первой картинке), для всех размеров экранов больших 1440, твоя верстка должна сойтись с макетом. Не нужно растягивать содержимое, при любых размерах экрана его ширина должна оставаться 1160. Для размеров меньших 1440 (или даже 1200 тут сам решай какие отступы по бокам, главное чтобы смотрелось хорошо) верстка - резиновая.
![image](https://user-images.githubusercontent.com/66846004/112718559-e506c780-8f04-11eb-9fee-914290b1eaf9.png)

То что у тебя сейчас
![image](https://user-images.githubusercontent.com/66846004/112718579-11224880-8f05-11eb-8fdb-c17514e39a3b.png)

**Comment by kate-fsd** [comment]
Поправить line-height
![image](https://user-images.githubusercontent.com/66846004/114017674-f93bb480-9874-11eb-97a8-0c304073b09d.png)

**Comment by kate-fsd** [comment]
Опустить подпись
![image](https://user-images.githubusercontent.com/66846004/114017780-196b7380-9875-11eb-8ba8-bf9941de1922.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/116778780-b25c6b80-aa7c-11eb-90be-8fd249272fd3.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/116778805-dfa91980-aa7c-11eb-96ad-662a9fdc0f1e.png)

сердечко не по центру

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/122059911-c6261c00-cdf5-11eb-9749-6ab785cdfcd7.png)
search-room
