### ISSUE TITLE
Календарь

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/UI-kit#27]
Календарь не соответствует макету

Беда с логикой, посмотри количество дней в неделе

При наведении на кнопки применить/очистить не соблюдается симметрия отступов. Этот пункт можно не выполнять, так как серого фона вообще не должно быть (об этом в ишью 6)
![image](https://user-images.githubusercontent.com/66846004/111608088-e724a400-87e9-11eb-894c-8d539114f37c.png)

**Comment by kate-fsd** [comment]
В календаре выделяю дату, перехожу на предыдущий месяц. Когда открываю снова, открывается тот месяц на котором я закрыла страницу. Лучше открывать ту на которой выделена дата

При закрытии календарь как то заметно съеживается, прыгает размер. Попробуй от этого избавиться

Слишком большая разница с макетом. Цифры дней плохо читаемы. 23 совсем пропала
![image](https://user-images.githubusercontent.com/66846004/112198713-7680eb80-8c1e-11eb-822e-cb35fe05dd27.png)
![image](https://user-images.githubusercontent.com/66846004/112198923-ab8d3e00-8c1e-11eb-89d9-0ad62fe588ba.png)

**Comment by Sprashivaite** [comment]
Не ясна первая проблема. Открывать на текущую дату? Или на выбранный диапазон. Или допустим я выбираю дату, но случайно закрыл календарь. Тогда снова придётся искать нужную дату.

**Comment by kate-fsd** [comment]
На выбранный диапазон. Это удобнее, и обычно календари работают именно так. Но это не суперважное требование, я ишью закрою, а ты хочешь сделай, хочешь так оставь
