### ISSUE TITLE
js

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/UI-kit#38]
Тут наверное хотел forEach использовать
![image](https://user-images.githubusercontent.com/66846004/114027825-77518880-9880-11eb-8794-52c5bf5179db.png)

**Comment by kate-fsd** [comment]
masked ? maskOptions:""
рядом с : тоже должны быть отступы. Еще старайся придерживаться одного типа, если options - это объект, то и вторую часть условия лучше сделать объектом

![image](https://user-images.githubusercontent.com/66846004/115960558-c6531b00-a51a-11eb-9077-996ec3383f5d.png)
поля объекта не нужно обрамлять в скобки

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/115961958-a8d57f80-a521-11eb-9f8b-3b02cf5082a3.png)
в этом коде нет смысла в том что ты каждый раз записываешь в this кнопку
в этой строке тоже this.stars.onmousedown = () => false;

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/115962028-feaa2780-a521-11eb-9982-04abbd9a289c.png)
этот код немного нелогичен, prevStar.previousElementSibling - предыдущий элемент от предыдущей звезды?)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/115962704-4e3e2280-a525-11eb-8414-5cd88d24ebd1.png)

**Comment by Sprashivaite** [comment]
> в этой строке тоже this.stars.onmousedown = () => false;

Не совсем понял проблему

**Comment by kate-fsd** [comment]
> > в этой строке тоже this.stars.onmousedown = () => false;
> 
> Не совсем понял проблему

а зачем нужен этот обработчик? И в любом случае он не работает, ты пытаешься его вызвать на коллекции элементов
