### ISSUE TITLE
dropdown

### ISSUE THREAD

**Issue by kate-fsd** [Sprashivaite/UI-kit#49]
![image](https://user-images.githubusercontent.com/66846004/116779274-074cb180-aa7e-11eb-93f0-429efaef30e0.png)
у тебя уже есть такой компонент, нужно использовать его, а не дублировать стили

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/116779369-affb1100-aa7e-11eb-9e10-ada269c89a4d.png)

Не нужно отключать эти правила. Разберись, зачем они нужны и исправь ошибки

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/116779515-43344680-aa7f-11eb-969c-fe93b6b6202d.png)

неподходящий метод массива

**Comment by kate-fsd** [comment]
this.title.innerHTML = this.defaultTitle;

лучше использовать метод для вставки как текста

**Comment by kate-fsd** [comment]
Похоже что у тебя нельзя установить начальные значения в дропдауны, если это так, нужно исправить

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/116779945-eab27880-aa81-11eb-8457-75f9fb750066.png)

Привязывать контекст нужно другим образом. Лучше - использовать декоратор bind или стрелочные функции

**Comment by kate-fsd** [comment]
вместо make plus лучше использовать глагол increase

**Comment by kate-fsd** [comment]
еще в RoomCard убери комменты

**Comment by kate-fsd** [comment]
handlerPlus неправильное имя

**Comment by kate-fsd** [comment]
Подскажи, а для чего нужны эти обработчики?
    this.dropdown.onmousedown = () => false;
    this.dropdown.onclick = () => false;

**Comment by Sprashivaite** [comment]
> Подскажи, а для чего нужны эти обработчики?
> this.dropdown.onmousedown = () => false;
> this.dropdown.onclick = () => false;

Убирает дефолтные обработчики, чтобы при кликах по кнопкам не выделялись текст и элементы

**Comment by kate-fsd** [comment]
Тогда лучше это сделать с помощью css(предпочтительнее) или onselectstart

**Comment by kate-fsd** [comment]
на странице http://localhost:8081/room-details.html в дропдауне нажимаю очистить получаю ошибку "Cannot POST /room-details.html"
