### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [Sprashivaite/UI-kit#60]
1. hideDatepicker вынести в отдельный метод. В обоих календарях.
![method](https://user-images.githubusercontent.com/51824674/127170693-2128c741-6088-4fca-8434-cbacecb6beda.png)

2. Число точек должно соответствовать числу картинок в галерее.
![dots](https://user-images.githubusercontent.com/51824674/127170874-ec6484c7-7f09-46a9-a5b6-e22fad5541d3.png)

3. Здесь тоже лучше метод массива использовать, просто выполнять действие при соответствии условию, лишние итерации здесь ни на что не повлияют.
![array method](https://user-images.githubusercontent.com/51824674/127171748-518d18a7-8c17-4705-802e-8121feb147ae.png)

**Comment by Sprashivaite** [comment]
2. Количество точек поправил. На самой странице везде по 4 картинки добавить?
